config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#dashboard"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  get "overview", to: "pages#overview"
  resources :pulses do
    member do
      get "loading", to: "pulses#loading"
    end
    resources :pulse_categories, only: [:index, :show]
    resources :questions, only: [:index, :show]
  end


  resources :categories, only: [:index, :show] do
    member do
      get 'questions', to: 'categories#question_first'
    end
  end

  resources :questions, only: [:index, :show] do
    resources :answers, only: [:create, :update, :destroy, :show]

  end

  get "dashboard/pulse", to: "dashboard#pulse", as: "pulse_dashboard"
end

app/views/shared/_navbar.html.erb
<%# <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid"> %>
    <%# <%= link_to root_path, class: "d-flex align-items-center" do %> 
     <%# <%= image_tag "pplogo.png", class: "avatar me-2" %>
    <%# <% end %> 


    <%# <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto"> %>
        <%# <% if user_signed_in? %> 
          <%# <li class="nav-item active"> %>
            <%# <%= link_to "About", "#", class: "nav-link" %> 
          <%# </li> %>
          <%# <li class="nav-item active-2"> %>
            <%# <%= link_to "Resources", "#", class: "nav-link" %> 
          <%# </li> %>
           <%# <li class="nav-item active-3"> %>
            <%# <%= link_to "Community", "#", class: "nav-link" %> 
          <%# </li> %>
          <%# <li class="nav-item"> %>
            <%# <%= link_to "New-Pulse", new_pulse_path, class: "nav-link" %> 
          <%# </li> %>
          <%# <li class="nav-item dropdown"> %>
          <%# <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> %>
            <%# <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu", id: "user-avatar" %> 
          <%# </a> %>
            <%# <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown"> %>
              <%# <%= link_to "Profile", edit_user_registration_path , class: "dropdown-item" %> 
              <%# <%= link_to "Pulses", pulses_path, class: "dropdown-item"  %>
              <%# <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %> 
            <%# </div> %>
          <%# </li> %>
        <%# <% else %> 
          <%# <li class="nav-item"> %>
            <%# <%= link_to "Login", new_user_session_path, class: "nav-link" %> 
          <%# </li> %>
        <%# <% end %> 
      <%# </ul>
    </div>
  </div>
</div> %>