config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#dashboard"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  get "overview", to: "pages#overview"
  resources :pulses do
    member do
      get "loading", to: "pulses#loading"
    end
    resources :pulse_categories, only: [:index, :show]
    resources :questions, only: [:index, :show]
  end


  resources :categories, only: [:index, :show] do
    member do
      get 'questions', to: 'categories#question_first'
    end
  end

  resources :questions, only: [:index, :show] do
    resources :answers, only: [:create, :update, :destroy, :show]

  end

  get "dashboard/pulse", to: "dashboard#pulse", as: "pulse_dashboard"
end

app/models/pulse.rb
class Pulse < ApplicationRecord
  belongs_to :user
  has_many :pulse_categories
  has_many :categories, through: :pulse_categories
  has_many :questions, through: :pulse_categories
  after_create :create_questions, unless: :seeding?
  # after_save :create_questions, if: :categories_changed?

  # # validates :job_role, presence: true
  # # validates :job_description, presence: true

  # def categories_changed?
  #   # Check if the associated pulse categories have changed
  #   pulse_categories.loaded? && (pulse_categories.pluck(:id) != previous_pulse_categories_ids)
  # end

  # def previous_pulse_categories_ids
  #   # This returns the IDs of the pulse categories before the save
  #   @previous_pulse_categories_ids ||= PulseCategory.where(pulse_id: id).pluck(:category_id)
  # end

  def seeding?
    ENV["SEEDING"] == 'true'
  end

  private

  def create_questions
    SetPulseQuestionsJob.perform_later(self)


  end

end

app/controllers/pulses_controller.rb
class PulsesController < ApplicationController
  def index
    @pulses = Pulse.all
  end

  def show
    @pulse = Pulse.find(params[:id])
    @categories = @pulse.categories.where(name: ['Soft skills', 'Technical skills', 'Psychometric skills'])
    @pulses = Pulse.where(user: current_user)
  end

  def new
    @pulse = Pulse.new
  end

  def create
    @pulse = Pulse.new(pulse_params)
    @pulse.user = current_user
    if @pulse.save
      # first_question = @pulse.questions.order(:id).first
      # if first_question
      #   redirect_to pulse_question_path(@pulse, first_question)
      # else
        redirect_to loading_pulse_path(@pulse)
      # end
    else
      render :new, status: :unprocessable_entity
    end

  end

  def edit
    @pulse = Pulse.find(params[:id])
  end

  def update
    @pulse = Pulse.find(params[:id])

    if @pulse.update(pulse_params)
      # Find the first category from the updated pulse
      first_category = @pulse.categories.first

      if first_category
        # Retrieve the first question for the selected category
        first_question = first_category.questions.order(:id).first
        if first_question
          redirect_to pulse_question_path(@pulse, first_question), notice: 'Pulse updated successfully.'
        else
          redirect_to pulses_path, notice: "Pulse updated, but no questions found for the selected category."
        end
      else
        redirect_to pulses_path, notice: "Pulse updated, but no categories found."
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @pulse = Pulse.find(params[:id])
    @pulse.destroy

    redirect_to pulses_path, status: :see_other
  end

  def loading
    @pulse = Pulse.find(params[:id])
  end

  private

  def pulse_params
    params.require(:pulse).permit(:job_role, :company_name, :company_description, category_ids: [])
  end
end

app/views/pulses/_ready.html.erb
<div id="<%= dom_id(pulse) %>" class="pulse">
  <%= turbo_stream_from dom_id(pulse) %>
  <% if pulse.questions.any? && pulse.questions.all?(&:content?) %>
  <div class="card-loader">
    <div id="begin" class="btn-black">
    <%= link_to 'Start!', pulse_question_path(pulse, pulse.questions.first) %>
    </div>
  </div>
  <% else %>
    <div class="card-loader">
      <div class="loader"></div>
    </div>
  <% end %>
</div>

app/views/pulses/_results.html.erb
<div id="result_<%= dom_id(pulse) %>" class="pulse">
  <%= turbo_stream_from "result_#{dom_id(pulse)}"%>
 <% if pulse.questions.all? { |question| question.answers.any? && question.answers.all? { |answer| answer.chat_review? && !answer.evaluation.nil?} } %>
    <div class="card-purple">
      <div class="align-end">
        <%=link_to 'Review answers', question_answer_path(pulse.questions.first, pulse.questions.first.answers.last ), data: {turbo: false}, class: "btn-black" %>
      </div>
      <%= bar_chart pulse.pulse_categories.map { |pulse_category| [pulse_category.category.name, pulse_category.average_rating.round(2)] },
      height: "300px",
      colors: ["#8e44ad"],
      library: {
        scales: {
          x: {
            ticks: { beginAtZero: true },
            max: 10
          }
        }
      } %>
    </div>
  <% else %>
    <div class="card-purple">
      <div class="loader-review-container data-controller="reload">
    <h4>Generating your feedback</h4>
        <div class="loader-review"></div>
      </div>
    </div>
  <% end %>
</div>

app/views/pulses/edit.html.erb
<%= turbo_frame_tag "main_content" do %>
  <div class="container">
    <h1 class="mb-5 mt-5">Update your Pulse</h1>
      <%= simple_form_for(@pulse) do |f| %>
      <%= f.input :job_role %>
      <%= f.input :company_name%>
      <%= f.input :company_description %>
      <%= f.association :categories, as: :check_boxes  %>
      <%= f.submit value:"Update your Pulse", class: "btn btn-warning", data: {turbo: false} %>
    <% end %>
  </div>
<% end %>

app/views/pulses/index.html.erb
<div class="pulses-container">
  <h1 class="text-center">welcome to all your pulses</h1>
  <% @pulses.each do |pulse| %>
    <%= link_to pulse_path(pulse) do %>
      <ul><%= pulse.company_name %> - <%= pulse.job_role %></ul>
    <% end %>
  <% end %>
</div>

app/views/pulses/loading.html.erb
<%= render "ready", pulse: @pulse %>

app/views/pulses/new.html.erb
<div class="container mt-3">
  <div class="new-pulse-container">

    <div class="form-background">
        <h1 class="gradient-text mb-4">New Pulse</h1>
        <%# <p> Prepare to ace your interview!</p> %>

        <%# <br> %>
        <%# <p> Fill in the details below to generate tailored questions based on the job and select categories to focus on key skills.</p> %>

      <%= simple_form_for(@pulse) do |f| %>
        <%= f.input :job_role, placeholder: "(What is the position you are applying for?)" %>
        <%= f.input :company_name, placeholder: "(Enter the name of the company you're preparing for.)" %>
        <%= f.input :company_description, placeholder: "(Give a brief description of the company or its industry.)" %>
        <div class="association">
          <%= f.association :categories, collection: Category.all, as: :check_boxes %>
        </div>
          <%# <%= f.hidden_field :category_ids, value: "", id: "category_ids" %> 
          <div class="create-pulse-button">
            <%= f.submit value: "Create Pulse", class: "btn-black" %>
          </div>
      <% end %>
    </div>


  </div>
</div>

app/views/pulses/show.html.erb
<div class="dashboard-container d-flex">
  <div class="sbar-container">
    <%= link_to  overview_path, data: {turbo_frame: "main_content"} do %>
      <h3 class="ms-5 mb-5 mt-4 overview-link">
      <span class="dashboard-icon"> <%= image_tag "pie-chart.png" %></span>
      Overview
      </h3>
    <% end %>
    <h3 class="ms-5">
      <span class="dashboard-icon"> <%= image_tag "pulse.png" %></span>
      Pulses
    </h3>
    <div class="pulses-list">
      <% @pulses.each do |pulse| %>
          <%= link_to pulse.job_role, pulse_path(pulse), data: {turbo_frame: "main_content"}, class:"btn-purple-gradient" %>
      <% end %>
    </div>
    <div class="d-flex">
      <%= link_to new_pulse_path, class: 'new-pulse-link d-flex align-items-center' do %>
        <span class="dashboard-icon"> <%= image_tag "add.png" %></span>
        New Pulse
      <% end %>
    </div>

    <hr>
      <div class="profile">
      <div class="image ml-2">
        <%= link_to image_tag("profile.png", class: "avatar", alt: "User Profile", id: "user-avatar"), edit_user_registration_path, class: "avatar" %>
      </div>

      <div class="title mt-1">
        <%= "#{current_user.first_name.capitalize} #{current_user.last_name}" %>
      </div>
    </div>

    <div class="d-flex justify-content-between mt-5">
        <a href="#">About</a>
        <a href="#">Resources</a>
        <%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete} %>
    </div>
  </div>
  <div class="main-content">
    <%= turbo_frame_tag "main_content" do %>
      <div class="card-purple d-flex justify-content-between">
        <div>
          <h1><%= @pulse.job_role.capitalize %> Pulse</h1>
          <p><%= @pulse.job_description %></p>
          <p>Company: <%= @pulse.company_name %></p>
          <p>Company Description: <%= @pulse.company_description %></p>
        </div>
          <div class="mt-0 mb-auto">
            <%= link_to "Practice", pulse_question_path(@pulse, @pulse.questions.first), data: {turbo: false}, class:"btn-black" %>
          </div>
      </div>

        <div class="d-flex justify-content-between m-5">
        <%= render "results", pulse: @pulse %>
        </div>
      </div>
    <% end %>
  </div>
</div>